name: docs
# https://github.com/julia-actions/julia-docdeploy
on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - main

jobs:
  Documenter:
      permissions:
        contents: write
      name: Documentation
      runs-on: ubuntu-latest
      steps:
        - name: Setup z3
          run: sudo apt-get -y install z3
        - name: Setup Yices
          run: sudo add-apt-repository ppa:sri-csl/formal-methods; sudo apt-get update; sudo apt-get install yices2
        - uses: actions/checkout@v4
        - uses: julia-actions/cache@v2
        - uses: julia-actions/julia-buildpkg@v1
        - uses: julia-actions/julia-docdeploy@v1
          env:
            GITHUB_TOKEN: ${{ secrets.DOCS_GITHUB_TOKEN }}
